.env.lib, .github/workflows/release.yml, package.json, src/index.tsx, src/lib/components/button/button.module.css, src/lib/components/grid/grid.module.css, src/lib/components/grid/index.tsx, src/lib/index.ts, vite.config.ts
- add GridFill component for separating items in GridHeader, etc.
- update Vite.js config for building either lib or pages
- add deploy of pages to release action
fix: remove roboto font from library
- prevent bundling web font within Ninja Kit
- TODO: add recommended documentation to add Roboto font via @fontsource/roboto
fix: button tap box flash
- prevent Button component from flashing default blue box when
tapping with mobile devices
=> feat: grid fill

README.md, package-lock.json, package.json, tsconfig.json
- remove typescript plugin for css modules
=> docs: readme logo and badges

package-lock.json, package.json, src/docs/app.tsx, src/lib/components/button/anchor.tsx, src/lib/components/button/button.module.css
- apply button gap regardless of icon presence
- append external link icon to button anchor with target of `_blank`
- make react-icons a dependency
chore: external anchors
- apply `_blank` target to all external button anchors
- show license button anchor only on home page
chore: sentry
- apply sentry error tracing to website
=> fix: button gap

package.json
- copy css assets
- map exports correctly
=> fix: color-scheme

src/docs/app.tsx, src/docs/pages/examples/color-scheme.tsx, src/docs/pages/examples/index.tsx, src/docs/pages/examples/radioset.tsx, src/lib/components/radioset/index.tsx, src/lib/components/radioset/radioset.module.css
- require name prop
- disabled styles
- add disabled state to example
- update color-scheme example with radioset
=> fix: radioset

src/docs/app.tsx, src/lib/components/article/article.module.css, src/lib/components/article/index.tsx, src/lib/components/button/anchor.tsx, src/lib/components/button/button.module.css, src/lib/components/button/index.tsx, src/lib/components/floating-action-button/floating-action-button.module.css, src/lib/components/footer/footer.module.css, src/lib/components/main/index.tsx, src/lib/components/main/main.module.css, src/lib/components/radioset/radioset.module.css
- pass layout components as props to Main and Article components
- rearrange where footer is displayed based on width
- remove extra right padding from AnchorButton with external icon
- prevent RadioSet options from wrapping
=> feat: layout props

jest.config.mjs, package-lock.json, package.json, src/docs/app.tsx, src/docs/pages/examples/anchor-button.tsx, src/docs/pages/examples/button.tsx, src/docs/pages/examples/index.tsx, src/docs/pages/examples/radioset.tsx, src/docs/pages/examples/text-input.tsx, src/lib/components/article/article.module.css, src/lib/components/button/anchor.test.tsx, src/lib/components/button/anchor.tsx, src/lib/components/button/button.tsx, src/lib/components/button/index.tsx, src/lib/components/card/card.module.css, src/lib/components/input/index.tsx, src/lib/components/input/input.module.css, src/lib/components/input/input.test.tsx, src/lib/components/input/text.tsx, src/lib/components/radioset/radioset.module.css, src/lib/components/radioset/radioset.tsx, src/lib/index.ts
- TextInput component
- fix `Article` body layout
- fix `RadioSet` disabled label appearance
- `Card` section inherit background color for `TextInput` outline label
- bump vite from 2.7.6 to 2.7.7
- bump @types/node from 17.0.4 to 17.0.5
- bump @typescript-eslint/parser from 5.8.0 to 5.8.1
- bump @typescript-eslint/eslint-plugin from 5.8.0 to 5.8.1
- bump @commitlint/cli from 15.0.0 to 16.0.0
=> Text input

package-lock.json, package.json, src/docs/app.tsx, src/docs/pages/examples/anchor-button.tsx, src/docs/pages/examples/button-menu.tsx, src/docs/pages/examples/button.tsx, src/docs/pages/examples/index.tsx, src/docs/pages/examples/input-menu.tsx, src/docs/pages/examples/menu-items.tsx, src/lib/components/button/anchor.tsx, src/lib/components/button/button.module.css, src/lib/components/button/button.tsx, src/lib/components/button/index.tsx, src/lib/components/input/index.tsx, src/lib/components/input/text.tsx, src/lib/components/menu/button.tsx, src/lib/components/menu/index.tsx, src/lib/components/menu/input.tsx, src/lib/components/menu/item.tsx, src/lib/components/menu/items.tsx, src/lib/components/menu/menu.module.css, src/lib/hooks/color-scheme.ts, src/lib/hooks/random-id.ts, src/lib/index.ts, src/lib/util/index.ts, tsconfig-types.json, tsconfig.json
- ButtonMenu
- InputMenu
- Button/AnchorButton leadingIcon/trailingIcon props
- useRandomId hook
- utils for DOM walking
=> feat: menus

src/docs/pages/examples/menu-items.tsx, src/lib/components/input/text.tsx, src/lib/components/menu/button.tsx, src/lib/components/menu/index.tsx, src/lib/components/menu/input.tsx, src/lib/hooks/random-id.ts, src/lib/index.ts
- random ids can't work for SSR as server/client-side values won't match
=> fix: remove useRandomId hook

src/lib/components/input/text.tsx, src/lib/components/main/index.tsx
- wrap Main/Input children props in fragments
=> fix: dev warnings

src/lib/components/header/header.module.css, src/lib/components/input/input.module.css, src/lib/components/nav/nav.module.css
- add background color to Header for inheritance
- tint TextInput filled background color
- fix tint/background color of Nav inconsistencies
=> fix: color tokens

src/lib/components/input/input.module.css
- prevent browsers from changing background color after autofilling
- ensure label translates after autofilling
=> fix: text input autofill

src/lib/components/input/text.tsx
- add trailing icon button type to prevent submitting form
=> fix: text input trailing button

src/docs/pages/examples/index.tsx, src/docs/pages/examples/typography.tsx, src/lib/components/typography/index.tsx
- fixes #128
- add `Typography` examples to docs
=> fix: typography

src/docs/pages/examples/input-menu.tsx, src/docs/pages/examples/text-input-state.tsx, src/docs/pages/examples/text-input.tsx, src/lib/components/input/index.ts, src/lib/components/input/input.module.css, src/lib/components/input/text.tsx
- `flex` prop added to TextInput/InputMenu far alternate width layouts
- refactor TextInput/InputMenu examples with shared state management
=> fix: text input flex

.eslintrc.json, global.d.ts, package-lock.json, package.json, playwright.config.ts, src/docs/pages/examples/input-menu/index.tsx, src/lib/components/button/button.spec.ts, src/lib/components/input/index.ts, src/lib/components/input/input.module.css, src/lib/components/input/text.tsx, src/lib/components/menu/index.ts, src/lib/components/menu/input.tsx, src/lib/components/menu/menu.tsx
- fix: remove text input label pointer events
- fix: return focus to text input control after selecting a menu option
- fix: handle more keyboard use cases with input menu
- test: simplify expect matcher and improve cross-browser support
=> fix: input menu and text input

package-lock.json, package.json, src/docs/pages/examples/button-menu/state.tsx, src/docs/pages/overview/dojo.module.css, src/lib/components/menu/button.tsx, src/lib/components/menu/index.ts, src/lib/components/menu/input.tsx, src/lib/components/menu/menu.tsx
- flip menu above control when at bottom of parent
- shift menu sideways to avoid appearing outside the viewport
=> fix: menu positioning

package-lock.json, package.json, src/docs/app.tsx, src/docs/pages/examples/anchor-button/index.tsx, src/docs/pages/examples/button-menu/index.tsx, src/docs/pages/examples/button-menu/state.tsx, src/docs/pages/examples/button/index.tsx, src/docs/pages/examples/checkbox/index.tsx, src/docs/pages/examples/index.tsx, src/docs/pages/examples/input-menu/index.tsx, src/docs/pages/examples/password-input/index.tsx, src/docs/pages/examples/password-input/state.tsx, src/docs/pages/examples/radioset/index.tsx, src/docs/pages/examples/text-input/index.tsx, src/docs/pages/examples/typography.tsx, src/lib/components/button/button.spec.ts, src/lib/components/input/index.ts, src/lib/components/input/input.module.css, src/lib/components/input/password.tsx, src/lib/components/input/text.tsx, src/lib/index.ts
- PasswordInput component
- fix: text input right padding with trailing icon
- redesign examples contents
- remove sentry from website
=> feat: password input

src/docs/pages/examples/input-menu/index.tsx, src/docs/pages/examples/input-menu/state.tsx, src/docs/pages/examples/password-input/index.tsx, src/docs/pages/examples/password-input/state.tsx, src/docs/pages/examples/radioset/index.tsx, src/docs/pages/examples/radioset/state.tsx, src/docs/pages/examples/text-input/index.tsx, src/docs/pages/examples/text-input/state.tsx, src/lib/components/input/index.ts, src/lib/components/input/input.module.css, src/lib/components/input/text.tsx
- disabled appearance of TextInput, PasswordInput and InputMenu
- update website examples to demonstrate various disabled components
=> fix: appearance of disabled inputs

src/docs/app.tsx, src/docs/pages/examples/anchor-button/index.tsx, src/docs/pages/examples/button-menu/index.tsx, src/docs/pages/examples/button/index.tsx, src/docs/pages/examples/checkbox/index.tsx, src/docs/pages/examples/index.tsx, src/docs/pages/examples/input-menu/index.tsx, src/docs/pages/examples/password-input/index.tsx, src/docs/pages/examples/radioset/index.tsx, src/docs/pages/examples/text-input/index.tsx, src/docs/pages/examples/typography.tsx, src/docs/pages/overview/index.tsx, src/docs/pages/sandbox/index.tsx, src/lib/components/card/index.tsx, src/lib/hooks/hash-ref.ts, src/lib/hooks/intersection-observer.ts, src/lib/index.ts
- `useIntersectionObserver` and `useHashRef` hooks
- wrap `Card` component in a forward ref
- update website url has as each section is scrolled to
- scroll component example into view on page load/reload
- move unique Article components down into individual routes/views
=> docs: examples permalinks

src/docs/pages/examples/text-input/index.tsx, src/lib/components/input/input.module.css, src/lib/components/input/text.tsx, vite.config.ts
- equal space between text input and helper/error messages
=> fix: input messages

src/docs/pages/examples/checkbox/index.tsx, src/lib/components/checkbox/checkbox.module.css, src/lib/components/checkbox/checkbox.tsx
- center align label children
- gap label children
=> fix: checkbox label

.eslintrc.json, src/docs/pages/examples/anchor-button/index.tsx, src/docs/pages/examples/button-menu/index.tsx, src/docs/pages/examples/button/index.tsx, src/docs/pages/examples/checkbox/index.tsx, src/docs/pages/examples/checkbox/state.tsx, src/docs/pages/examples/dialog/index.tsx, src/docs/pages/examples/dialog/state.tsx, src/docs/pages/examples/index.tsx, src/docs/pages/examples/input-menu/index.tsx, src/docs/pages/examples/password-input/index.tsx, src/docs/pages/examples/radioset/index.tsx, src/docs/pages/examples/text-input/index.tsx, src/docs/pages/examples/typography.tsx, src/lib/components/article/article.module.css, src/lib/components/aside/aside.module.css, src/lib/components/button/anchor.tsx, src/lib/components/button/button.tsx, src/lib/components/button/index.ts, src/lib/components/card/card.module.css, src/lib/components/card/index.tsx, src/lib/components/dialog/dialog.module.css, src/lib/components/dialog/dialog.tsx, src/lib/components/dialog/index.ts, src/lib/components/menu/menu.module.css, src/lib/hooks/hash-ref.ts, src/lib/hooks/intersection-observer.ts, src/lib/index.ts, src/lib/util/index.ts, tsconfig.json
- add `Dialog` component and website example
- update `Card` component and styles to better match specs
- update `Button` component label with `ReactNode` type
- update `Typography` examples with cleaner appearance
- add `classNames` utility function
- add generic type to `useHashRef` and `useIntersectionObserver`
=> feat: dialog

src/lib/components/dialog/dialog.module.css
- move certain desktop-only styles to mobile-default
- fixes disabled X icon and missing animation in mobile
=> fix: mobile dialog

src/docs/pages/overview/dojo.module.css, src/lib/components/button/button.module.css, src/lib/components/checkbox/checkbox.module.css, src/lib/components/floating-action-button/floating-action-button.module.css, src/lib/components/menu/menu.module.css, src/lib/components/nav/nav.module.css, src/lib/components/radioset/radioset.module.css, src/lib/style.css
- fix `Checkbox` and `Radioset` appearance in mobile/desktop Safari
- css transition consistency
- fix website overview appearance regression
=> fix: webkit appearance

src/docs/pages/examples/dialog/index.tsx, src/docs/pages/examples/dialog/state.tsx, src/lib/components/article/article.module.css, src/lib/components/aside/aside.module.css, src/lib/components/button/button.module.css, src/lib/components/dialog/dialog.module.css, src/lib/components/dialog/dialog.tsx, src/lib/components/floating-action-button/floating-action-button.module.css, src/lib/components/header/header.module.css, src/lib/components/main/main.module.css, src/lib/components/nav/nav.module.css, src/lib/style.css
- global scrolling class for composing
- horizontal scrolling customization to match vertical
- gap between actions of dialog footer
- remove dev tools warning for dialog footer actions
=> fix: scrolling

src/lib/components/checkbox/checkbox.module.css, src/lib/components/checkbox/checkbox.tsx, src/lib/components/checkbox/index.ts, src/lib/components/dialog/index.ts
- prevent checkbox input from changing size at certain widths
- prevent checkbox label from wrapping
- refactor checkbox code without forwarded ref and with hook
=> fix: checkbox wrap

README.md, src/docs/app.tsx, src/docs/pages/overview/index.tsx
- simplify tagline
- update share text
=> docs: tagline

CONTRIBUTING.md, package-lock.json, package.json, playwright.config.ts, vite.config.ts
- consolidate local server to strictly use port 4173 in dev/prod
=> build: bump vite from 2.7.13 to 2.8.0

src/lib/components/checkbox/checkbox.module.css, src/lib/components/checkbox/checkbox.tsx, src/lib/components/checkbox/index.ts
- prevent checkbox hover style when over label
- refactor more state to the hook
=> fix: checkbox hover

src/docs/pages/examples/checkbox/index.tsx, src/docs/pages/examples/checkbox/state.tsx, src/docs/pages/examples/password-input/index.tsx, src/docs/pages/examples/password-input/state.tsx, src/docs/pages/examples/text-input/index.tsx, src/docs/pages/examples/text-input/state.tsx, src/lib/color-scheme/default.css, src/lib/color-scheme/enterprise.css, src/lib/components/checkbox/checkbox.module.css, src/lib/components/checkbox/checkbox.tsx, src/lib/components/checkbox/index.ts, src/lib/components/input/index.ts, src/lib/components/input/input.module.css, src/lib/components/input/password.tsx, src/lib/components/input/text.tsx, src/lib/components/tooltip.tsx/index.tsx, src/lib/components/tooltip.tsx/tooltip.module.css
- warning message for `TextInput`, `PasswordInput` and `Checkbox`
- icons prepend error, warning and helper messages
=> feat: warning message

src/docs/pages/examples/button-menu/index.tsx, src/docs/pages/examples/input-menu/index.tsx, src/lib/components/menu/button.tsx, src/lib/components/menu/menu.tsx
- fake change event handler for button menu component
- update menu examples to log changes in the console
=> fix: button menu on change

vite.config.ts
- remove temporary work-a-round for React 18 build issue
=> build: vite config

package-lock.json, package.json, src/docs/index.html
- fix invalid HTML and formatting
=> build(deps-dev): bump vite from 3.09 to 3.1.4
